In [6]:
import numpy as np
import sys
a=np.array([1,2,3])#Similer to the lisit
a

array([1, 2, 3])

In [9]:
import time
SIZE = 1000000

l1=range(SIZE)
l2=range(SIZE)

a1= np.arange(SIZE)
a2= np.arange(SIZE)

start= time.time()
res=[(x+y) for x,y in zip(l1,l2)]
print("Python List took" , (time.time()-start)*1000)

# Numpy List time
start= time.time()
result=a1+a2
print("Numoy Array Took",(time.time()-start)*1000 )

Python List took 185.1801872253418
Numoy Array Took 3.0002593994140625


In [11]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim
a.itemsize

4

In [13]:
a=np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a.itemsize

8

In [14]:
a.size

6

In [15]:
a
a.shape

(3, 2)

In [19]:
a=np.array([[1,2],[3,4],[5,6]], dtype=complex)
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
b=np.ones((3,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
c=np.arange(1,5)
d=np.linspace(1,6,10)
d

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [25]:
a=np.array([[1,2],[3,4],[5,6]])
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [26]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [27]:
a.sum(axis=0)

array([ 9, 12])

In [28]:
a.sum(axis=1)

array([ 3,  7, 11])

In [30]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [31]:
np.std(a)

1.707825127659933

In [33]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a+b
a*b

array([[ 5, 12],
       [21, 32]])

In [34]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [35]:
# Slicing/Stacking/Indexing with boolean array
a=np.array([6,7,8])
a[0:2]


array([6, 7])

In [36]:
a[-1]

8

In [37]:
a=np.array([[6,7,8],[1,2,3],[9,4,5]])
a[1,2]

3

In [38]:
a[0:2,2]

array([8, 3])

In [39]:
a[-1]

array([9, 4, 5])

In [40]:
  a[-1,0:2]

array([9, 4])

In [41]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [4, 5]])

In [42]:
#itration in array
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 4 5]


In [43]:
for self in a.flat:
    print(self)

6
7
8
1
2
3
9
4
5


In [45]:
#Stacking 2 arrat

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
b=np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [48]:
np.vstack((a,b))


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [49]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [51]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [55]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [56]:
# indexing with boolean array
n=np.arange(12).reshape(3,4)
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
b=n>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
n[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [61]:
n[b]=-1
n

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [62]:
a=np.linspace(2,5,4)
a

array([2., 3., 4., 5.])